sudo: required
language: node_js
node_js:
- 8
cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle
branches:
  only:
  - release
before_script:
- npm install -g gulp-cli
- npm install -g node-sass
before_install:
- rvm install 2.3.7
- gem install bundler -v2.0.2
before_deploy:
- export PATH="$PATH:$HOME/.rvm/bin"
script: gulp build
install:
- bundle install
- npm install
deploy:
  provider: pages
  local-dir: "./_site"
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: c2e587c4b2b04e9cd6b6e26d5c2d574b204ce626
  keep-history: true
  on:
    branch: release
env:
  matrix:
    secure: dYLl602QmjKCb1AFroh+I5jMzbRooWsrWPZuFsKBNLU5gzgrDcBgL21w4TyuwHk1SkXnq5loL5Yasg9gP9/F9QhgNEH8ITlpAO/RKzOw1VoT7Q9xzVfFZIR2BeYJsvHd67tkT/d6aPhhChLAqji79060tD5jRE4NaTEd9ApdT5a9cQYWyGmDHL/lVoQ9SeG3+ACfz67VGF7WsOeK97iuOUCLd4iZRzGW0aj94fmAoXk0SX/wMf1cRjvYz2AXnHXnaxpcQWo7NidmufXcFkEHUhmQuucdxw26YCD2TlMzapEfH0o20NG4s7oug/DFFROaupxJAROwnHUBtR/RalK1IBp2zAzA0mStJP2OIzt3vP7/jG3qT4Ximmx2bnfIWyaAmWCiHs/wXAT6CkkT8EuKDBpRYmBnU150s6JveARvabXsLECrow4paVzwcOn88TxGdPYJyLfJId7HtTr5knvPtxNpdZIfwlXKS0txhlpriRhOqItpiRB9hW7PlVtfiC7x/ERCpf3XTI5urHTfDVSu1mpbznerNhRj+2RejePRiBXaYI1E1cyci+E1bVnWDZRSSWvDfhFI5mq1uc4jqmT005mlNhw2GxzqC+VxX194Qzg/7E9KsZGCOvGmB0t6ll2aLzItTSl2BmGzEYGN3CC20kfKLZGbHJijXGjepTag/ek=
