name: docs-theme
title: Docs Theme
source: ./src
destination: ./_site
encoding: UTF-8

ENV: development

url: ""
baseurl:  ""

# Prototype data
company:
  name: Help Scout


# Permalinks
permalink: pretty

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

exclude:
  - _site
  - .asset-cache
  - .cache
  - .gitignore
  - _assets/vendor
  - framework/archived
  - js
  - node_modules
  - prod-config
  - scss
  - site
  - tmp
  - "*.xml"

keep_files:
  - css
  - fonts
  # - images
  - js
  - "*.xml"
