# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Docs
email: sean.e.halpin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seanehalpin.github.io/docs" # the base hostname & protocol for your site
twitter_username: seanehalpin
github_username:  seanehalpin
info-button: Info
meta: "/assets/meta.png"

# Build settings
markdown: kramdown
exclude: ["README.md", "package.json", "gulpfile.js", "node_modules/"]

plugins_dir: ./_plugins

jekyll_get:
  - data: github
    json: 'https://api.github.com/users/seanehalpin/repos'
    cache: false
